const $ = (s) => document.querySelector(s);
const state = JSON.parse(localStorage.getItem('tomato-state') || '{}');
state.tasks ||= [{ id: Date.now(), text: '整理项目方案', done: false, pomodoros: 0 }, { id: Date.now() + 1, text: '阅读 20 页专业书', done: false, pomodoros: 0 }];
state.settings ||= { focus: 25, short: 5, long: 15, sunEvery: 1, sunEnabled: true, notifications: false, sunCadenceVersion: 2 };
if ((state.settings.sunCadenceVersion || 0) < 2) { state.settings.sunEvery = 1; state.settings.sunCadenceVersion = 2; } state.settings.sunEvery ||= 1; state.settings.sunEnabled ??= true; state.settings.notifications ??= false;
state.today ||= { date: new Date().toDateString(), pomodoros: 0, minutes: 0 }; state.history ||= {};
state.garden ||= {};
const legacyGardenUnits = (Number(state.garden.small) || 0) + (Number(state.garden.large) || 0) * 4 + (Number(state.garden.golden) || 0) * 16;
if (!Number.isFinite(state.garden.plantStage)) { state.garden.plantStage = legacyGardenUnits % 4; state.garden.matured = Math.floor(legacyGardenUnits / 4); }
state.garden.plantStage = Math.max(0, Math.min(4, Number(state.garden.plantStage) || 0));
state.garden.matured = Math.max(0, Number(state.garden.matured) || 0);
state.garden.harvested = Math.max(0, Number(state.garden.harvested) || state.garden.matured);
if (state.today.date !== new Date().toDateString()) state.today = { date: new Date().toDateString(), pomodoros: 0, minutes: 0 };
let mode = ['focus', 'short', 'long'].includes(state.activeMode) ? state.activeMode : 'focus';
let remaining = Number.isFinite(state.remaining) ? state.remaining : state.settings[mode] * 60;
let running = false, timer, endAt = null, selectedId = state.selectedId || null, cycles = state.cycles || 0, toastTimer, audioContext, noiseSource, ambientAudio, activeAmbient, alarmTimer, alarmTimeout, sunReminderTimer, alarmActive = false, pendingAlarmAction = null;
const circumference = 703.72;
function save(){Object.assign(state,{selectedId,cycles,activeMode:mode,remaining});localStorage.setItem('tomato-state',JSON.stringify(state));}
function showToast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>t.classList.remove('show'),3000);}
function format(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;}
function modeName(){return {focus:'专注时间',short:'短暂休息',long:'长休息'}[mode];}
function setMode(next,fresh=true){clearInterval(timer);timer=null;running=false;endAt=null;mode=next;if(fresh)remaining=state.settings[mode]*60;document.querySelectorAll('.mode-tab').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('active',on);b.setAttribute('aria-selected',on)});renderTimer();save();}
function renderTimer(){const total=state.settings[mode]*60;$('#timeDisplay').textContent=format(Math.max(0,remaining));$('#modeLabel').textContent=running?modeName():remaining===total?'准备开始':'已暂停';$('#progressRing').style.strokeDashoffset=circumference*(1-Math.max(0,remaining)/total);$('#progressRing').style.stroke=mode==='focus'?'':'#9daa8a';$('#startButton').innerHTML=running?'<span>Ⅱ</span> 暂停':`<span>▶</span> ${mode==='focus'?'开始专注':'开始休息'}`;$('#cycleDots').textContent=Array.from({length:4},(_,i)=>i<cycles%4?'●':'○').join(' ');document.title=running?`${format(remaining)} · ${modeName()} — 番茄`:'番茄 · 专注空间';}
function ensureAudio(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;audioContext ||= new C();audioContext.resume();return audioContext;}
function ring(frequency=660,duration=.55){const context=ensureAudio();if(!context)return;const o=context.createOscillator(),g=context.createGain();o.frequency.value=frequency;g.gain.setValueAtTime(.1,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+duration);o.connect(g).connect(context.destination);o.start();o.stop(context.currentTime+duration);}
function notify(title,body){if(state.settings.notifications&&'Notification'in window&&Notification.permission==='granted')new Notification(title,{body});}
function growTomato(){state.garden.plantStage=Math.min(4,state.garden.plantStage+1);}
function renderGarden(growing=false){const stage=state.garden.plantStage;const plot=$('#gardenPlot');const src=['tomato-seed.svg','tomato-sprout.svg','tomato-plant.svg','tomato-tree.svg','tomato-tree.svg'][stage];const label=['种子','幼苗','成长植株','成熟番茄树','成熟番茄树'][stage];plot.innerHTML=`<div class="garden-soil${stage===4?' mature':''}"><img src="assets/${src}" alt="${label}"></div><div class="garden-soil empty"></div><div class="garden-soil empty"></div>`;plot.classList.toggle('growing',growing);$('#gardenTotal').textContent=`${state.garden.harvested} 个`;$('#gardenStageLabel').textContent=stage===4?'番茄树成熟了':'番茄成长中';$('#gardenStageCount').textContent=`${Math.min(stage,4)} / 4 次专注`;$('#growthMeter').innerHTML=''.padEnd(stage,'■')+'□'.repeat(4-stage);const next=['完成 1 次专注，获得一颗番茄种子。','再完成 1 次专注，番茄苗会继续成长。','再完成 1 次专注，长成番茄植株。','再完成 1 次专注，番茄树就成熟了。','可以收获一颗番茄，土地会恢复空闲。'][stage];$('#gardenProgress').textContent=next;$('#harvestButton').classList.toggle('hidden',stage!==4);}
function harvestMatureTomato(){if(state.garden.plantStage!==4)return;state.garden.harvested++;state.garden.plantStage=0;save();renderGarden(true);showToast('收获一个番茄，开始种植下一株。');}
function shouldShowSunReminder(){return state.settings.sunEnabled&&cycles%state.settings.sunEvery===0;}
function showSunReminder(){if(!shouldShowSunReminder())return;clearTimeout(sunReminderTimer);$('#sunModal').classList.remove('hidden');notify('护眼时间到了','离开屏幕，去窗边望向远处和自然光；请不要直视太阳。');sunReminderTimer=setTimeout(()=>$('#sunModal').classList.add('hidden'),10000);}
function startAlarm(title,message,afterStop=null){stopAlarm(false);alarmActive=true;pendingAlarmAction=afterStop;$('#alarmTitle').textContent=title;$('#alarmMessage').textContent=message;$('#alarmModal').classList.remove('hidden');const pulse=()=>ring(880,.6);pulse();alarmTimer=setInterval(pulse,1100);alarmTimeout=setTimeout(()=>stopAlarm(),10000);}
function stopAlarm(runAction=true){if(!alarmActive)return;clearInterval(alarmTimer);clearTimeout(alarmTimeout);alarmTimer=null;alarmTimeout=null;alarmActive=false;$('#alarmModal').classList.add('hidden');const action=pendingAlarmAction;pendingAlarmAction=null;if(runAction&&action)action();}
function finish(){clearInterval(timer);timer=null;running=false;endAt=null;remaining=0;if(mode==='focus'){cycles++;state.today.pomodoros++;state.today.minutes+=state.settings.focus;growTomato();const key=new Date().toISOString().slice(0,10);state.history[key]=(state.history[key]||0)+1;const task=state.tasks.find(t=>t.id===selectedId);if(task)task.pomodoros++;const next=cycles%4===0?'long':'short';setMode(next);const text=state.garden.plantStage===4?'专注完成！番茄树成熟了，可以收获。':state.garden.plantStage===1?'专注完成！获得番茄种子 🌱':'你的番茄苗成长了一点。';showToast(text);notify('一个番茄完成',text);startAlarm('一个番茄完成','休息已经开始，提示音将在 10 秒后停止。',showSunReminder);toggleTimer();}else{setMode('focus');showToast('休息结束，准备开始新一轮专注。');notify('休息结束','可以开始下一轮专注了。');startAlarm('休息结束','请点击“开始专注”进入下一轮。');}save();renderTimer();renderCurrent();renderGarden(true);renderTasks();renderStats();}
function syncTimer(){if(!running||!endAt)return;const next=Math.max(0,Math.ceil((endAt-Date.now())/1000));if(next<=0){finish();return;}if(next!==remaining){remaining=next;save();}renderTimer();}
function toggleTimer(){if(running){syncTimer();clearInterval(timer);timer=null;running=false;endAt=null;}else{ensureAudio();running=true;endAt=Date.now()+remaining*1000;syncTimer();timer=setInterval(syncTimer,250);}renderTimer();save();}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)syncTimer();});
function escapeHtml(value){const d=document.createElement('div');d.textContent=value;return d.innerHTML;}
function renderTasks(){const box=$('#taskList');box.innerHTML='';state.tasks.forEach(task=>{const item=document.createElement('div');item.className='task'+(task.done?' done':'');item.innerHTML=`<input class="check" aria-label="完成${escapeHtml(task.text)}" type="checkbox" ${task.done?'checked':''}><span class="task-name">${escapeHtml(task.text)}</span><span class="task-count">${task.pomodoros} 个番茄</span><button class="choose">${selectedId===task.id?'已选择':'专注此项'}</button><button class="delete" title="删除${escapeHtml(task.text)}">×</button>`;item.querySelector('.check').onchange=()=>{task.done=!task.done;save();renderTasks();renderStats()};item.querySelector('.choose').onclick=()=>{selectedId=task.id;save();renderCurrent();renderTasks();showView('focus')};item.querySelector('.delete').onclick=()=>{state.tasks=state.tasks.filter(t=>t.id!==task.id);if(selectedId===task.id)selectedId=null;save();renderTasks();renderCurrent()};box.append(item)});}
function renderCurrent(){const task=state.tasks.find(t=>t.id===selectedId);$('#currentTaskText').textContent=task?task.text:'选择一项待办，开始专注';$('#todayFocus').textContent=state.today.pomodoros;$('#todayMinutes').textContent=state.today.minutes;}
function renderStats(){$('#summaryPomodoros').textContent=Object.values(state.history).reduce((a,b)=>a+b,0)+state.today.pomodoros;$('#summaryMinutes').textContent=Object.values(state.history).reduce((a,b)=>a+b*state.settings.focus,0)+state.today.minutes;$('#summaryDone').textContent=state.tasks.filter(t=>t.done).length;const chart=$('#barChart'),labels=$('#chartLabels');chart.innerHTML='';labels.innerHTML='';const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);days.push({label:['日','一','二','三','四','五','六'][d.getDay()],value:i===0?state.today.pomodoros:(state.history[key]||0)})}const max=Math.max(1,...days.map(d=>d.value));days.forEach((d,i)=>{const bar=document.createElement('div');bar.className='bar'+(i===6?' today':'');bar.style.height=`${Math.max(5,d.value/max*100)}%`;bar.title=`${d.value} 个番茄`;chart.append(bar);const label=document.createElement('span');label.textContent=`周${d.label}`;labels.append(label)});}
function renderSunSetting(){$('#sunEvery').textContent=state.settings.sunEvery;const button=$('#sunToggle');button.textContent=state.settings.sunEnabled?'已开启':'已暂停';button.classList.toggle('off',!state.settings.sunEnabled);button.setAttribute('aria-pressed',String(state.settings.sunEnabled));}
function showView(view){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#viewTitle').textContent={focus:'专注片刻',tasks:'待办清单',stats:'专注记录'}[view];}
const ambientTracks={rain:{label:'细雨',icon:'☂',url:'https://assets.mixkit.co/active_storage/sfx/2393/2393-preview.mp3'},waves:{label:'海浪',icon:'〰',url:'https://assets.mixkit.co/active_storage/sfx/1185/1185-preview.mp3'},cafe:{label:'咖啡馆',icon:'♨',url:'https://assets.mixkit.co/active_storage/sfx/444/444-preview.mp3'},birds:{label:'晨鸟',icon:'♩',url:'https://assets.mixkit.co/active_storage/sfx/2472/2472-preview.mp3'},white:{label:'白噪音',icon:'∿'}};
function resetSoundButtons(){document.querySelectorAll('.sound').forEach(button=>{const track=ambientTracks[button.dataset.sound];button.classList.remove('active');button.textContent=`${track.icon} ${track.label}`;});}
function stopAmbient(){if(ambientAudio){ambientAudio.pause();ambientAudio.src='';ambientAudio=null;}if(noiseSource){noiseSource.stop();noiseSource.disconnect();noiseSource=null;}activeAmbient=null;resetSoundButtons();}
function startWhiteNoise(){const context=ensureAudio();if(!context){showToast('当前浏览器不支持播放环境音');return false;}const buffer=context.createBuffer(1,context.sampleRate*2,context.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;noiseSource=context.createBufferSource();noiseSource.buffer=buffer;noiseSource.loop=true;const gain=context.createGain();gain.gain.value=.055;noiseSource.connect(gain).connect(context.destination);noiseSource.start();return true;}
function toggleAmbient(button){const key=button.dataset.sound,track=ambientTracks[key];if(activeAmbient===key){stopAmbient();showToast(`${track.label}已暂停`);return;}stopAmbient();if(key==='white'){if(!startWhiteNoise())return;}else{ambientAudio=new Audio(track.url);ambientAudio.loop=true;ambientAudio.volume=.28;ambientAudio.play().catch(()=>{stopAmbient();showToast('音频加载失败，请检查网络后重试。');});}activeAmbient=key;button.classList.add('active');button.textContent=`${track.icon} ${track.label} · 播放中`;showToast(`${track.label}正在播放`);}
$('#dateLabel').textContent=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(new Date());
document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('.mode-tab').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
function setFocusScreen(enabled){document.body.classList.toggle('focus-screen',enabled);$('#fullscreenButton').title=enabled?'退出沉浸模式':'进入沉浸模式';$('#fullscreenButton').setAttribute('aria-label',enabled?'退出沉浸模式':'进入沉浸模式');}
$('#startButton').onclick=()=>toggleTimer();$('#resetButton').onclick=()=>setMode(mode);$('#selectTaskButton').onclick=()=>showView('tasks');
$('#harvestButton').onclick=()=>harvestMatureTomato();
$('#addTaskButton').onclick=()=>{$('#taskForm').classList.toggle('hidden');$('#taskInput').focus();};$('#taskForm').onsubmit=e=>{e.preventDefault();const text=$('#taskInput').value.trim();if(!text)return;state.tasks.unshift({id:Date.now(),text,done:false,pomodoros:0});$('#taskInput').value='';$('#taskForm').classList.add('hidden');save();renderTasks();};
document.querySelectorAll('.sound').forEach(button=>button.onclick=()=>toggleAmbient(button));
$('#fullscreenButton').onclick=()=>setFocusScreen(!document.body.classList.contains('focus-screen'));$('#exitFocusButton').onclick=()=>setFocusScreen(false);$('#sunToggle').onclick=()=>{state.settings.sunEnabled=!state.settings.sunEnabled;save();renderSunSetting();showToast(state.settings.sunEnabled?'护眼提醒已开启':'护眼提醒已暂停');};
$('#settingsButton').onclick=()=>{$('#focusInput').value=state.settings.focus;$('#shortInput').value=state.settings.short;$('#longInput').value=state.settings.long;$('#sunInput').value=state.settings.sunEvery;$('#notificationInput').checked=state.settings.notifications;$('#settingsModal').classList.remove('hidden');};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(`#${b.dataset.close}`).classList.add('hidden'));$('#sunDoneButton').onclick=()=>{clearTimeout(sunReminderTimer);$('#sunModal').classList.add('hidden');};$('#stopAlarmButton').onclick=()=>stopAlarm();
$('#settingsForm').onsubmit=async e=>{e.preventDefault();const values={focus:+$('#focusInput').value,short:+$('#shortInput').value,long:+$('#longInput').value,sunEvery:+$('#sunInput').value};if(Object.values(values).some(v=>!Number.isFinite(v)||v<1))return showToast('请输入大于 0 的分钟数。');if($('#notificationInput').checked&&'Notification'in window&&Notification.permission==='default'){const permission=await Notification.requestPermission();state.settings.notifications=permission==='granted';if(permission!=='granted')showToast('浏览器通知未授权，仍会在页面内提醒。');}else state.settings.notifications=$('#notificationInput').checked&&('Notification'in window)&&Notification.permission==='granted';Object.assign(state.settings,values);setMode(mode);save();renderSunSetting();$('#settingsModal').classList.add('hidden');showToast('你的专注节奏已保存。');};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)&&!document.querySelector('.modal:not(.hidden)')){e.preventDefault();toggleTimer();}if(e.key==='Escape'){if(document.body.classList.contains('focus-screen'))setFocusScreen(false);if(!alarmActive)document.querySelectorAll('.modal').forEach(m=>m.classList.add('hidden'));}});
let authClient=null,authMode='login';
function authError(error){$('#authError').textContent=error?.message||'操作失败，请稍后重试。';}
function renderAuth(user){$('#accountMessage').textContent=user?`你好，${user.email.split('@')[0]}`:'登录后同步你的番茄园';$('#accountButton').textContent=user?'退出登录':'登录 / 注册';$('#accountButton').dataset.action=user?'logout':'open';}
function setAuthMode(mode){authMode=mode;$('#authTitle').textContent=mode==='login'?'登录你的番茄园':'创建番茄账号';$('#authSubmit').textContent=mode==='login'?'登录':'注册';$('#authSwitch').textContent=mode==='login'?'没有账号？注册':'已有账号？登录';$('#authError').textContent='';}
async function initAuth(){const config=window.SUPABASE_CONFIG;if(!config?.url||!config?.anonKey||config.url.includes('YOUR_PROJECT'))return;authClient=window.supabase.createClient(config.url,config.anonKey);const {data}=await authClient.auth.getSession();renderAuth(data.session?.user||null);authClient.auth.onAuthStateChange((_event,session)=>renderAuth(session?.user||null));}
$('#accountButton').onclick=async()=>{if(!authClient)return showToast('请先配置 Supabase 账号服务。');if($('#accountButton').dataset.action==='logout'){const {error}=await authClient.auth.signOut();if(error)showToast(error.message);else{renderAuth(null);showToast('已退出登录。');}return;}setAuthMode('login');$('#authModal').classList.remove('hidden');$('#authEmail').focus();};
$('#authSwitch').onclick=()=>setAuthMode(authMode==='login'?'signup':'login');
$('#authForm').onsubmit=async e=>{e.preventDefault();const email=$('#authEmail').value.trim(),password=$('#authPassword').value;const result=authMode==='login'?await authClient.auth.signInWithPassword({email,password}):await authClient.auth.signUp({email,password});if(result.error)return authError(result.error);$('#authModal').classList.add('hidden');showToast(authMode==='signup'&&!result.data.session?'注册成功，请检查邮箱完成验证。':authMode==='login'?'登录成功。':'注册成功。');};
renderTimer();renderTasks();renderCurrent();renderGarden();renderStats();renderSunSetting();initAuth();
